image: Ubuntu2204  # образ для сборки

stack: node 22.15.0  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
 # команда установки зависимостей
#  - corepack enable
#  - yarn set version 4.8.1
#  - yarn
  - npm install

build: off  # отключаем встроенную в appveyor систему сборки

test_script:
#  - yarn lint  # скрипт
  - npm run test
  - npm run lint

build_script:
#  - yarn build   # команда сборки
  - npm run build

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
